### ISSUE TITLE
Template performance

### ISSUE THREAD

**Issue by ntntn** [yordan-kanchelov/pixi-typescript-boilerplate#727]
Spector js shows too much webgl commands on template's scene and drawcalls, though it got alsmost nothing, why is that?
I am using Phaser at work and have performance problems, especially on apple devices, so I wanted to try PIXI
But so much operations aren't even close to Phaser's debug

Rename to .html, open in browser to watch result or try using Spector.js yourself
[result.html.txt](https://github.com/yordan-kanchelov/pixi-typescript-boilerplate/files/7512733/result.html.txt)
![screen](https://user-images.githubusercontent.com/58854581/141114757-d2570e07-38f1-4bd3-9c16-982118a971ad.png)

**Comment by yordan-kanchelov** [comment]
Hi @ntntn. Sorry for the late response. 

I am pretty sure it has to do with the fact the template is using the PIXI.Application class which is re-rendering the whole scene on each requestAnimationFrame.  

https://pixijs.io/guides/basics/render-loop.html

I haven't done a lot of optimizations myself, but this is the first thing I would recommend you to check. 

PS maybe a good place to ask for some explanations is in the [pixi.js discussions group](https://github.com/pixijs/pixijs/discussions/)

**Comment by yordan-kanchelov** [comment]
@ntntn there are some draw calls because of the used filters in the layers example
